### ISSUE TITLE
Server tests fails on eslint step with Windows

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/gladys-4-playground#117]
All files in node_modules in services are linted... the ignore-pattern option may not work as well on Windows.

**Comment by Pierre-Gilles** [comment]
I added in https://github.com/GladysAssistant/gladys-4-playground/commit/39a633678357e34452c456c3b62dab539aa495a9 a .eslintignore instead of the --ignore-pattern, and simplified the eslint command to `eslint .`.

It should work on windows! Let me know if yes!

**Comment by Pierre-Gilles** [comment]
Is it working now? :)

**Comment by atrovato** [comment]
Sorry, but I can't try until next week. Be sure, I'll keep you aware.

**Comment by atrovato** [comment]
It's quite better for eslint, but I have two messages after "npm test" :

C:\Users\alext\Workspaces\gladys-4-playground\server\services\zwave\index.js
  7:25  error  Unable to resolve path to module 'openzwave-shared'  import/no-unresolved

C:\Users\alext\Workspaces\gladys-4-playground\server\test\benchmark\triggers.js
  68:8  warning  Unexpected constant condition  no-constant-condition

✖ 2 problems (1 error, 1 warning)

So this point is closed for me, but I created a new one #126
