### ISSUE TITLE
npm install --prefix fails on Windows

### ISSUE THREAD

**Issue by atrovato** [GladysAssistant/gladys-4-playground#56]
Hello,
the command to install services (npm install --prefix SERVICE_PATH) doesn't work on Windows.

It looks like it's an open issue https://github.com/npm/npm/issues/20245

**Comment by Pierre-Gilles** [comment]
Oh weird. The issue is not really about the same thing, it says "doesn't work with --save on windows"

What's your exact error?

**Comment by atrovato** [comment]
<warn> install_service_dependencies.js:20 (directories.forEach) { Error: Command failed: npm install --prefix C:\Users\alext\Workspaces\gladys-4-playground\server\services\bluetooth
npm ERR! Can't install C:\Users\alext\Workspaces\gladys-4-playground\server: Missing package version

**Comment by NilkOne** [comment]
Same problem under Windows for all gladys services :

Command failed: npm install --prefix C:\gladys-4-playground\server\services\zwave
npm ERR! Can't install C:\gladys-4-playground\server: Missing package version

same for usb, telegram, philips-hue, mqtt, example, darksky, zwave
